name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_trigger]
  schedule:
    - cron: '0 10,12,20 * * *'
  workflow_run:
    workflows: ["main"]
    branches: [main]
    types:
      - requested

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
