name: WakaTime-Stats

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_trigger]

jobs:
  update-readme:
    name: WakaTime-Stats
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          # Branch - newer GitHub repositories have "main" as default branch, change to main in that case, default is master
          BRANCH: "main"
          COMMIT_MSG: "自動でコーディングステータスをアップデートしました。:floppy_disk:"
