name: WakaTime-Stats

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_trigger]
  schedule:
    - cron: '0 10,12,20 * * *'

jobs:
  update-readme:
    name: WakaTime-Stats
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: "main"
          COMMIT_MSG: "自動でコーディングステータスをアップデートしました。:floppy_disk:"
